### PR TITLE
Fixed ui bugs

### PR DESCRIPTION
**Pull request by Ahsan161815**
## Description

Fixed ui bugs #434
1. crane - russian tabs text goes out of bounds (Fixed by making it scrollable)
2. shrine - glow effect is not lined up with the box angle, or clipped, thus goes out of the box (see top left area of the screenshot) (Not Fixed have suggestion)
3. settings menu - safe area at the top is not applied (Fixed)
4. reply - back button at the top goes under the status bar (was Already Fixed)
5. reply - bottom sheet is not scrollable (Was Already Fixed)

## Tests

*Please describe the tests that you added or updated to verify your changes.*

## Issues

1. crane - russian tabs text goes out of bounds
2. shrine - glow effect is not lined up with the box angle, or clipped, thus goes out of the box (see top left area of the screenshot)
3. settings menu - safe area at the top is not applied
4. reply - back button at the top goes under the status bar
5. reply - bottom sheet is not scrollable

---
Screenshot_1681559143Screenshot_1681556066
Screenshot_1681558945
Screenshot_1681559136

### CODE REVIEW

**Comment by guidezpl** [comment]
Please fix `   info • Use 'const' with the constructor to improve performance • lib/studies/crane/backdrop.dart:364:30 • prefer_const_constructors`

**Comment by guidezpl** [comment]
Also, what is your suggestion for the following?

| shrine - glow effect is not lined up with the box angle, or clipped, thus goes out of the box (see top left area of the screenshot) (Not Fixed have suggestion)

**Comment by Ahsan161815** [comment]
> Also, what is your suggestion for the following?
> 
> | shrine - glow effect is not lined up with the box angle, or clipped, thus goes out of the box (see top left area of the screenshot) (Not Fixed have suggestion)

Maybe We can use BouncingScrollPhysics() instead of default scroll behaviour. That way we don't have glow effect anymore.

**Comment by guidezpl** [comment]
SGTM

**Comment by Ahsan161815** [comment]
> SGTM

@guidezpl I have updated the code to fix Shrine Glow effect.
below is screen recording.
[shrine_glow2.webm](https://user-images.githubusercontent.com/96950460/233001752-792fae96-9640-4954-9b62-23e136b0f374.webm)

**Review by guidezpl — APPROVED** [review]

**Pull request merged**
