### PR TITLE
Fix two null safety analysis issues and update goldens

### PR DESCRIPTION
**Pull request by devoncarew**
Fix two null safety analysis issues.

*List which issues are fixed by this PR. You must list at least one issue.*

- these analysis issues are currently breaking the Dart SDK's `flutter-analyze` CI bot (https://ci.chromium.org/ui/p/dart/builders/ci.sandbox/flutter-analyze/15160/overview)

```
warning • The receiver can't be null, so the null-aware operator '?.' is unnecessary •
       lib/feature_discovery/feature_discovery.dart:224:34 • invalid_null_aware_operator
warning • The receiver can't be null, so the null-aware operator '?.' is unnecessary •
       lib/feature_discovery/feature_discovery.dart:240:36 • invalid_null_aware_operator
```

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by zanderso — APPROVED** [review]

**Review by guidezpl — APPROVED** [review]

**Comment by guidezpl** [comment]
Integrated the changes from https://github.com/flutter/gallery/pull/597 to fix the test deadlock

**Comment by devoncarew** [comment]
Thanks for fixing the PR up can landing it!

I'm assuming it's only a smaller set of folks that can trigger the repo's checks?

**Comment by guidezpl** [comment]
I think so, but I don't have access to those settings. @godofredoc might know more

**Comment by copperyp** [comment]
build & run fail :(

Hi devoncarew
cd gallery
flutter config --enable-windows-desktop
flutter pub get
flutter run -d windows

lib/feature_discovery/feature_discovery.dart(224,35): error G0EB489DC: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is p
otentially null. [D:\src\gallery\build\windows\flutter\flutter_assemble.vcxproj]
lib/feature_discovery/feature_discovery.dart(240,37): error G0EB489DC: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is p
otentially null. [D:\src\gallery\build\windows\flutter\flutter_assemble.vcxproj]

env
[√] Flutter (Channel stable, 2.10.1, on Microsoft Windows [Version 10.0.19044.1526], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.9)
[√] Android Studio (version 4.2)
[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!

i revert file [feature_discovery.dart] to previous was build & run success!

**Comment by guidezpl** [comment]
Please read the README

**Pull request merged**
