### PR TITLE
Replace selectable text

### PR DESCRIPTION
**Pull request by OlegZaimNLT**
Removed all SelectableText. Added a SelectionArea per MaterialApp and one for settings.
Fixes https://github.com/flutter/gallery/issues/698
Clone https://github.com/flutter/gallery/pull/699

### CODE REVIEW

**Comment by OlegZaimNLT** [comment]
@guidezpl  Hey, could you check what happen with the test check?

**Comment by guidezpl** [comment]
I don't have bandwidth to investigate at the moment. I encourage you to try to repro the error locally.

**Comment by guidezpl** [comment]
@chunhtai, do you have a clue as to the following error?

```
[APP] Bad state: A RenderObject does not have any constraints before it has been laid out.
[APP]     at Object.wrapException (http://localhost:9999/main.dart.js:8823:17)
[APP]     at RenderParagraph.get$constraints (http://localhost:9999/main.dart.js:129964:17)
[APP]     at RenderParagraph.getBoxesForSelection$1 (http://localhost:9999/main.dart.js:131589:107)
[APP]     at _SelectableFragment.get$_paragraph$_rect (http://localhost:9999/main.dart.js:132050:20)
[APP]     at _SelectableFragment.getTransformTo$1 (http://localhost:9999/main.dart.js:132025:57)
[APP]     at _SelectableRegionContainerDelegate._compareScreenOrder$2 (http://localhost:9999/main.dart.js:166659:49)
[APP]     at tear_off.<anonymous> (http://localhost:9999/main.dart.js:9142:45)
[APP]     at Object.Sort__insertionSort (http://localhost:9999/main.dart.js:7981:37)
[APP]     at Object.Sort__doSort (http://localhost:9999/main.dart.js:7971:11)
[APP]     at Object.Sort_sort (http://localhost:9999/main.dart.js:7967:9)
```

**Comment by chunhtai** [comment]
it looks like some layout order issue,  it looks like some components are not laid out with in the same frame they were added to the widget tree. It will be good if there is a minimum repro

**Comment by chunhtai** [comment]
I think we will no longer need this once this is merged https://github.com/flutter/flutter/issues/104547

**Pull request closed without merging**
