### PR TITLE
Regular maintenance

### PR DESCRIPTION
**Pull request by guidezpl**
- update mac & iOS runners
- update packages, notably `google_fonts` to 3.0.1
- replace deprecated M2 `TextStyle` names
- regen some Android build files
  - fix build issues
  - bump Kotlin and Gradle versions
- update GitHub workflow actions to use latest runners, and setup Java 11 which is now required by Gradle for building Android
- update goldens due to imperceptible rendering changes
- update translations (8 more strings coming in ~2 weeks)

### CODE REVIEW

**Comment by guidezpl** [comment]
@godofredoc I've updated our workflows to always use the latest images, so could you update the required statuses accordingly?

**Comment by godofredoc** [comment]
> @godofredoc I've updated our workflows to always use the latest images, so could you update the required statuses accordingly?

Is it possible to make the test names generic? as it is the tests will be broken every time the version changes behind the scenes

**Comment by guidezpl** [comment]
Using `x-latest` makes them generic, so this should be the last time they require modifying.

**Comment by guidezpl** [comment]
Whoops, forgot one, should be good now.

**Comment by godofredoc** [comment]
> Whoops, forgot one, should be good now.

Updated!

**Review by jason-simmons — APPROVED** [review]

**Pull request merged**
