### PR TITLE
Added textinputaction in shrine

### PR DESCRIPTION
**Pull request by Alabhya268**
Added text input action in shrine login.

https://user-images.githubusercontent.com/57143358/107870411-2cd61000-6ebe-11eb-9baa-0fff5ca84fad.mp4

### CODE REVIEW

**Comment by Alabhya268** [comment]
@rami-a , Please review this PR.

**Review by guidezpl — APPROVED** [review]
LGTM though, could you please remove the pubspec.lock changes?

**Comment by Alabhya268** [comment]
> LGTM though, could you please remove the pubspec.lock changes?

ok

**Comment by Alabhya268** [comment]
@guidezpl , I've now reverted pubspec.lock changes. Please review the PR again.

**Pull request merged**
