### PR TITLE
Fix typography_demo body_text

### PR DESCRIPTION
**Pull request by mi6ock**
Fixed it because the description and style didn't match up.
In addition, the order was adjusted to the other.
Thank you!

### CODE REVIEW

**Comment by mi6ock** [comment]
@googlebot I fixed it..

**Comment by rami-a** [comment]
It looks like the CLA bot didn't work, could you please try again @mi6ock

**Comment by rami-a** [comment]
Additionally please run `flutter pub run grinder verify-code-segments` to ensure the code samples are updated and the CI checks pass. Thanks!

**Comment by mi6ock** [comment]
@googlebot I fixed it..

**Comment by mi6ock** [comment]
@googlebot I fixed it..

**Comment by rami-a** [comment]
Sorry, it looks like the email author on your commit does not match the email that you used to sign the CLA, you'll have to make sure those emails match.

**Comment by mi6ock** [comment]
Should I remake my PR again?

**Comment by rami-a** [comment]
It might be easier to remake the PR and ensure that the commit author matches the one you signed the CLA with. The alternative is to sign the CLA again with the commit author email, I'm not entirely sure how one does that though. It's up to you!

I apologize for the confusion, and I appreciate the fix!

**Comment by mi6ock** [comment]
Thank you so much for explaining it so carefully!
I'm going to remake the PR.

**Pull request closed without merging**
