### PR TITLE
Update compileSdkVersion to 31 and gradle lockfiles

### PR DESCRIPTION
**Pull request by andreidiaconu**
https://github.com/flutter/flutter/pull/89511 requires `compileSdkVersion 31` and it also introduces new android dependencies which means the gradle lockfiles need to be updated.

Helps with relanding https://github.com/flutter/flutter/pull/89511 which was reverted in https://github.com/flutter/flutter/pull/93098

List which issues are fixed by this PR. You must list at least one issue.
- https://github.com/flutter/flutter/issues/49411

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by guidezpl — APPROVED** [review]
LGTM

**Comment by andreidiaconu** [comment]
The `flutter_gallery` integration test copy inside the flutter framework repo also needed multidex support, but this repo seems to not need that (compiles fine on my machine). Seems like dependencies are sufficiently different between the two.

**Comment by andreidiaconu** [comment]
https://github.com/flutter/flutter/pull/93117 reland PR depends on this PR.

**Comment by amanv8060** [comment]
@guidezpl Flutter gallery for android doesn't compile after this pr , i can successfully run gallery on android at commit 4fd74910b0ec7302f01e8fff47cf719c1ffd5e39

**Comment by andreidiaconu** [comment]
@amanv8060 Please try the latest flutter master and let me know if you still can't compile.

**Comment by amanv8060** [comment]
@andreidiaconu Thanks, I can now run now, it's weird but I tried earlier and was unable to build the app with errors 
similar to 
> Did not resolve 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.5.30' which is part of the dependency lock state

Also, See #558

**Comment by andreidiaconu** [comment]
Thank you for also posting the actual error. I can now safely confirm my initial hunch: This PR updated the gallery repo to be compatible with the newest flutter master, but because that is how gradle lockfiles work, it also means that the repo is incompatible with older versions of flutter. I think this happens every time the lockfiles need to be updated, but maybe maintainers of this repo can confirm.

The reason why you had problems using flutter master until today is that the flutter change that required this PR hit a few bumps in the road, got reverted, relanded, etc - but it is now merged correctly and as long as you use flutter master for a while (until Display Features https://github.com/flutter/engine/pull/29585 are promoted to other channels).

**Pull request merged**
