### PR TITLE
Enable spacebar to scroll on the homepage

### PR DESCRIPTION
**Pull request by guidezpl**
https://github.com/flutter/flutter/issues/108735

### CODE REVIEW

**Review by Piinks — COMMENTED** [review]
I am not familiar with this app, why are there 2 `primary`? Are both present on the home screen at the same time? If so, this will probably cause a crash.
Is there test coverage for this change?

**Comment by guidezpl** [comment]
No, it's two different layouts. Manually tested, I don't know how to test keyboard entry

**Review by Piinks — COMMENTED** [review]
If it is untested, what prevents this from regressing in the future?

**Comment by guidezpl** [comment]
Praying? 😄

I tried adding a test but can't get it to pass: https://github.com/flutter/gallery/blob/78900fd40ce12e7bebeed888784fdf8417798a37/test_integration/interactions_test.dart. I tried key up + key down, with/without `PhysicalKey`, etc.

**Review by Piinks — COMMENTED** [review]
Hmm, without testing, the Gallery is going to just continue to experience code rot like this. It really should be tested.
Maybe instead of an integration test, you can just use a widget test? Here is a very similar test from the framework: https://github.com/flutter/flutter/blob/ba5181b7885340bacd370eac779c319dfd82670e/packages/flutter/test/widgets/shortcuts_test.dart#L984

**Comment by guidezpl** [comment]
I spent a good amount of time trying to get the test to work, and even checking the multiple `ScrollController`s found, the the pixel value is always 0. I give up 🤷‍♂️

**Pull request closed without merging**
