### PR TITLE
Overflow web view fix

### PR DESCRIPTION
**Pull request by gozeloglu**
Hi,

I fixed the problem of overflow on the web view. The related issue is https://github.com/flutter/gallery/issues/420 . Can you review my pull request?

### CODE REVIEW

**Comment by gozeloglu** [comment]
Hi @rami-a and @guidezpl . I am not able to set you as a reviewer. Can you review my changes?

**Review by guidezpl — APPROVED** [review]
```
  _    ___ _____ __  __ 
 | |  / __|_   _|  \/  |
 | |_| (_ | | | | |\/| |
 |____\___| |_| |_|  |_|
                        
```

Can you run `flutter pub run grinder update-code-segments`?

**Comment by gozeloglu** [comment]
In Turkish error message says that "The system cannot find the file specified." 

image


> ```
>   _    ___ _____ __  __ 
>  | |  / __|_   _|  \/  |
>  | |_| (_ | | | | |\/| |
>  |____\___| |_| |_|  |_|
>                         
> ```
> 
> Can you run `flutter pub run grinder update-code-segments`?

**Comment by guidezpl** [comment]
Hmm can you try `flutter format lib/codeviewer/code_segments.dart` and  `flutter format lib\codeviewer\code_segments.dart` on their own? Might be a separator issue

**Comment by gozeloglu** [comment]
> Hmm can you try `flutter format lib/codeviewer/code_segments.dart` and `flutter format lib\codeviewer\code_segments.dart` on their own? Might be a separator issue

image

I got this.

**Comment by guidezpl** [comment]
Can you commit what you have and push?

**Comment by gozeloglu** [comment]
> Can you commit what you have and push?

I did

**Comment by guidezpl** [comment]
https://github.com/flutter/gallery/blob/03d1151b02e3ddb06ea82b2d4da441d1c09383ca/lib/codeviewer/code_segments.dart looks unformatted, if you can format then commit and push, that should do the trick

**Comment by gozeloglu** [comment]
> 
> 
> https://github.com/flutter/gallery/blob/03d1151b02e3ddb06ea82b2d4da441d1c09383ca/lib/codeviewer/code_segments.dart looks unformatted, if you can format then commit and push, that should do the trick

How can I format? Do I need to touch the code and make changes? But, it is a huge file, 2.55 MB :(

**Comment by guidezpl** [comment]
Not by hand that's for sure aha. Your first `flutter format` in https://github.com/flutter/gallery/pull/427#issuecomment-777840932 looks like it worked. Just run that without the grinder command

**Comment by guidezpl** [comment]
Good to go, thanks!

**Pull request merged**
