### PR TITLE
rename local functions with `_`s

### PR DESCRIPTION
**Pull request by pq**
These will be flagged by the next linter release which updates `non_constant_identifier_names` to flag local functions.

See also:

* https://github.com/flutter/flutter/pull/102615
* https://dart-review.googlesource.com/c/sdk/+/242391
* dart-lang/linter#3360

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Review by goderbauer — APPROVED** [review]
LGTM

Thanks for cleaning this up!

**Comment by pq** [comment]
@goderbauer: is the goldens failure legitimate?  Any advice?

**Comment by guidezpl** [comment]
The goldens at the bottom of https://github.com/flutter/gallery/actions/runs/2233733806 looks to be showing slight changes in shadow rendering

**Comment by pq** [comment]
Good deal. Updated 🤞

**Comment by goderbauer** [comment]
Looks like the golden check is still unhappy even though there is no visible difference...

@guidezpl could you help out here?

**Comment by pq** [comment]
@guidezpl, @goderbauer: I regenerated (on Mac OS) and am still seeing failures...

I'm also a little puzzled as to why my PR would provoke a need to regenerate?

**Comment by guidezpl** [comment]
The icons render differently on the `home_page_desktop_dark` and `home_page_desktop_light` images. 

I'm hesitant to merge this even with new screenshots, because we've often found they're the cause of upstream work landing and being reverted. Meaning, we end up having to revert screenshots too. We should probably make the Goldens check not required, or at least allow team members to merge without all status checks.

@godofredoc can you help with that? Team members don't have access to settings for the repo.

**Comment by pq** [comment]
@guidezpl, @godofredoc : any thoughts here?  I'm happy to back out my goldens changes.

**Comment by godofredoc** [comment]
> @guidezpl, @godofredoc : any thoughts here? I'm happy to back out my goldens changes.

Removed golden tests from the required list.

**Pull request merged**
