### PR TITLE
Create build checking workflow

### PR DESCRIPTION
**Pull request by guidezpl**
Fixes https://github.com/flutter/gallery/issues/622

### CODE REVIEW

**Comment by guidezpl** [comment]
@godofredoc Could you make these new checks required to pass in the branch protection settings?

**Comment by godofredoc** [comment]
> @godofredoc Could you make these new checks required to pass in the branch protection settings?

Sure can you please verify the list: "Build apk --debug", "Build ios --no-codesign","Build macos", "Build web"?

**Review by godofredoc — APPROVED** [review]

**Comment by guidezpl** [comment]
@godofredoc yes, all pass

**Comment by godofredoc** [comment]
> Build web

Sorry for the delay. I just added the checks!

**Pull request merged**
