### PR TITLE
Remove rotation from Transformation demo description since it's not implemented

### PR DESCRIPTION
**Pull request by justinmc**
## Description

The transformation demo does not include rotation, but the description and subtitle says it does.  This PR removes mention of rotation.

Rotation is not currently supported by InteractiveViewer under the hood, though someday I'd like it to!

@guidezpl What's the process for updating an existing string like this?  I couldn't figure it out by reading the [l10n readme](https://github.com/flutter/gallery/tree/main/lib/l10n#readme).

## Tests

None.

## Issues
Fixes https://github.com/flutter/gallery/issues/967

### CODE REVIEW

**Review by guidezpl — APPROVED** [review]
Did you see https://github.com/flutter/gallery/tree/main/lib/l10n#obtaining-translations-for-flutter-org-members and `third_party/dart/flutter_gallery/README.md`?

**Comment by justinmc** [comment]
Yes, but it didn't seem to work for me.  Sorry, I'm probably just inexperienced with l10n stuff.

Running `flutter pub run grinder l10n` overwrites intl_en_US.xml with the old strings.

Running `flutter gen-l10n` gives:

```
Because l10n.yaml exists, the options defined there will be used instead.
To use the command line arguments, delete the l10n.yaml file in the Flutter project.
``

And doesn't seem to make any changes.

**Comment by guidezpl** [comment]
Me too, it's been a while. So it's not super clear (feel free to update the instructions), but the `arb` files serve as source, and in particular `intl_en.arb` serves as sources for the singular `intl_en.US.xml` file. So once you add a string to the former, `flutter pub run grinder l10n` updates the latter, which can then be imported into Google, translated, etc.

**Comment by justinmc** [comment]
@guidezpl Let me know if the PR looks good now to the best of your knowledge.  I update the `arb` file as well, and I added a section in the README about udpating messages as far as I understand it.

**Review by guidezpl — APPROVED** [review]
Yep, 
```
  _    ___ _____ __  __ 
 | |  / __|_   _|  \/  |
 | |_| (_ | | | | |\/| |
 |____\___| |_| |_|  |_|
                        
```

**Comment by justinmc** [comment]
@guidezpl It looks like goldens are failing.  I guess this text is included in some golden images?  Can you confirm that the changes are expected?  When I run the goldens locally with `flutter test test_goldens`, I get failures even on main.

If you confirm it's ok, it looks like I can update the goldens with `flutter test --update-goldens test_goldens`.

**Comment by guidezpl** [comment]
The goldens at https://github.com/flutter/gallery/actions/runs/5246680988 look good to me. Typically this is because some change hit Flutter @ main, and we can just update the goldens from that `goldens.zip` file. It's easier to use that since it's was CI tests against

**Pull request merged**
