### PR TITLE
Supress `deprecated_member_use` lint

### PR DESCRIPTION
**Pull request by LongCatIsLooong**
## Description

Addresses https://github.com/flutter/gallery/issues/981. There's code that's scaling non-text content using text scale factor so I'm not sure what the best way to migrate those code is.

## Tests

*Please describe the tests that you added or updated to verify your changes.*

## Issues
Fixes #

---

>**Note**: Please find the development and releasing instructions at https://github.com/flutter/gallery#development

### CODE REVIEW

**Comment by LongCatIsLooong** [comment]
Hi @guidezpl do you by chance know why the golden tests are failing? This isn't supposed to change the UI at all.

**Comment by guidezpl** [comment]
Since the gallery builds against Flutter master, it often happens that they have to be updated due to upstream changes

**Review by guidezpl — APPROVED** [review]
Can you please create an issue for replacing these with something appropriate?

**Comment by LongCatIsLooong** [comment]
@guidezpl created https://github.com/flutter/gallery/issues/983 . Thanks for the help!

**Pull request merged**
