### PR TITLE
Immovable textfield demo bug

### LINKED ISSUE #393: on android device - flutter web keyboard hide textfield
Hello

on my android device - flutter web keyboard hide textfield

edit password : 

edit confirm password: 

i have the same bug on my projet (flutter web)

### PR DESCRIPTION
**Pull request by rish07**
Addresses and closes #393

### CODE REVIEW

**Comment by rish07** [comment]
@guidezpl The TextFormFieldDemo on line 24 in text_field_demo.dart is directly given in the body of the scaffold. Since it has no place to move above, when the keyboard opens, the password field comes under it. 

If I wrap the whole thing in a SingleScrollable, it's given rendering error. This might be the issue

**Comment by rish07** [comment]
@googlebot I signed it!

**Comment by rish07** [comment]
@guidezpl The latest commit seems to fix the issue in all the demos. There are some formatting errors that I am making, can you help me with that?

**Comment by kishanhitk** [comment]
You can simply run `flutter format .` inside your root project directory to format all the dart files in your whole project.

**Comment by rish07** [comment]
@kishanhitk I have changed the channel to master and formatted the code.

**Comment by guidezpl** [comment]
Thanks for the PR! Unfortunately, this didn't to fix the underlying issue, which is actually a bit more complicated than expected. I'll get a PR with a bit of refactoring and a fix out in the next 2 weeks

**Pull request closed without merging**
